LSTM for Time Series Data is [here](https://colab.research.google.com/drive/1uKRCjXnUdxWFoNv298q4dNOJyfWAPHtX?usp=sharing)

# Classification

Please download the file text_data.csv from https://drive.google.com/file/d/1F3Zsb6zEdu-yKyrHi3RzpCm9g3M6Vmr5/view?usp=sharing

In [ ]:
! gdown --id 1F3Zsb6zEdu-yKyrHi3RzpCm9g3M6Vmr5

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1F3Zsb6zEdu-yKyrHi3RzpCm9g3M6Vmr5
To: /content/text_data.csv
100% 2.51M/2.51M [00:00<00:00, 179MB/s]

In [ ]:
import pandas as pd

df=pd.read_csv('text_data.csv')
df['class'].value_counts()

class
punpromotion.csv    2302
CH3Thailand.csv     1934
ejan2016.csv         319
Name: count, dtype: int64

In [ ]:
df.head()

                                             message            class
0            อย่า โกรธ แม่ ขาย 😭😭 ดู ย้อนหลัง ที่นี่  CH3Thailand.csv
1   แอคชั่น เต็ม แถม ซึ้ง ฉาก หวาน ดู เบื้องหลัง ...  CH3Thailand.csv
2   ร้องไห้ ไหว ทด กลายเป็น ทาส เด็ก ดู ย้อนหลัง ...  CH3Thailand.csv
3   รื้อ กระเป๋า เผ่า ส่อง  ไอเทม เด็ด ดู ติดตาม ...  CH3Thailand.csv
4   มีความผิด ที่จะ โดน เฆี่ยน ทด ใจเด็ด  ดู ย้อน...  CH3Thailand.csv

In [ ]:
df['word_length'] = df['message'].str.split()
df['word_length'] = df['word_length'].str.len()
df.dropna(inplace=True)

In [ ]:
df['word_length'].sort_values(ascending=False)

2574    355.0
4089    337.0
2113    282.0
2021    233.0
1943    219.0
        ...
2400      2.0
2307      2.0
2721      2.0
143       2.0
4500      2.0
Name: word_length, Length: 4554, dtype: float64

In [ ]:
df.message.values

array([' อย่า โกรธ แม่ ขาย 😭😭 ดู ย้อนหลัง ที่นี่',
       ' แอคชั่น เต็ม แถม ซึ้ง ฉาก หวาน ดู เบื้องหลัง ลิขิต จันทร์ ฟัง นักแสดง เล่าเรื่อง สนุก กอง ถ่าย ติดตาม กอง วิก  ลิขิต จันทร์ วันพรุ่งนี้ เวลา 09.15 น. ',
       ' ร้องไห้ ไหว ทด กลายเป็น ทาส เด็ก ดู ย้อนหลัง ที่นี่', ...,
       '  บัตรเครดิต ส่วนลด ไม่ต้อง เสียใจ ปัน โปร >> ขั้นตอน ปัน โปร <<  รายละเอียด สถานที่ ส่วนลด บัตรเครดิต ยอด ชำระเงิน facebook message >> รายละเอียด แบ่งปัน <<  สถานที่ Siam Paragon Siam Center Siam SQ 1, CentralWorld  เวลา ศุกร์ เสาร์ อาทิตย์ เวลา 11.00 น.  21.00  ชำระ ค่า อาหาร สินค้า ส่วนลด เงินสด ค่าธรรมเนียม แบ่งปัน >> หมายเหตุ <<  แบ่งปัน ส่วนลด การแลก คะแนน  สงวนสิทธิ์ การเปลี่ยนแปลง แบ่งปัน ส่วนลด แจ้งให้ทราบ ล่วงหน้า',
       '  เบื่อ ไหม พลาด ส่วนลด บัตรเครดิต ปัน โปร',
       ' แบ่งปัน ส่วนลด โปรโมชั่น บัตรเครดิต ร้านอาหาร ร้านค้า เพื่อน ติดตาม รายละเอียด ส่วนลด ช่วงเวลา สถานที่ แบ่งปัน รายสัปดาห์ ที่นี่ ค่าธรรมเนียม แบ่งปัน ^^'],
      dtype=object)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import SpatialDropout1D

MAX_WORDS = 2500
MAX_SEQUENCE_LENGTH = 355
EMBEDDING_DIM = 100

tokenizer = Tokenizer(num_words=MAX_WORDS, filters='!"#$%&()*+,-./:;<=>?@[]^_`{|}~')
tokenizer.fit_on_texts(df.message.values)
word_index = tokenizer.word_index
X = tokenizer.texts_to_sequences(df.message.values)

In [ ]:
df.message.values[0]

' อย่า โกรธ แม่ ขาย 😭😭 ดู ย้อนหลัง ที่นี่'

In [ ]:
len(word_index)

15610

In [ ]:
X[0]

[52, 2129, 115, 108, 401, 1, 22, 102]

In [ ]:
X = pad_sequences(X, maxlen=MAX_SEQUENCE_LENGTH)
Y = pd.get_dummies(df['class']).values
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.10, random_state = 42)

In [ ]:
X[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,   52, 2129,  115,  108,  401,
          1,   22,  102], dtype=int32)

In [ ]:
model = Sequential()
model.add(Embedding(MAX_WORDS, EMBEDDING_DIM, input_length=X_train.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

epochs = 5
batch_size = 64

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Epoch 1/5
58/58 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.8970 - loss: 0.3999 - val_accuracy: 0.9683 - val_loss: 0.0848
Epoch 2/5
58/58 ━━━━━━━━━━━━━━━━━━━━ 73s 1s/step - accuracy: 0.9797 - loss: 0.0617 - val_accuracy: 0.9951 - val_loss: 0.0353
Epoch 3/5
58/58 ━━━━━━━━━━━━━━━━━━━━ 73s 1s/step - accuracy: 0.9889 - loss: 0.0308 - val_accuracy: 0.9927 - val_loss: 0.0341
Epoch 4/5
58/58 ━━━━━━━━━━━━━━━━━━━━ 80s 1s/step - accuracy: 0.9924 - loss: 0.0223 - val_accuracy: 0.9927 - val_loss: 0.0311
Epoch 5/5
58/58 ━━━━━━━━━━━━━━━━━━━━ 81s 1s/step - accuracy: 0.9927 - loss: 0.0229 - val_accuracy: 0.9927 - val_loss: 0.0313

In [ ]:
accr = model.evaluate(X_test,Y_test)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 210ms/step - accuracy: 0.9868 - loss: 0.0505
Test set
  Loss: 0.050
  Accuracy: 0.987

In [ ]:
posts=['เชิญ ดู ละคร ย้อนหลัง วันนี้ ทุ่ม','อย่า พลาด อาหาร เด็ด ราคา โดน']
X_new_test = tokenizer.texts_to_sequences(posts)
X_new_test = pad_sequences(X_new_test, maxlen=MAX_SEQUENCE_LENGTH)
results = model.predict(X_new_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 792ms/step

In [ ]:
results

array([[9.9941432e-01, 3.2014027e-04, 2.6557778e-04],
       [7.7260941e-02, 4.1852348e-02, 8.8088667e-01]], dtype=float32)

In [ ]:
df['class'].unique()

array(['CH3Thailand.csv', 'ejan2016.csv', 'punpromotion.csv'],
      dtype=object)

# Word Prediction

In [ ]:
import pandas as pd

df=pd.read_csv('text_data.csv')
df.dropna(inplace=True)
df['word_length'] = df['message'].str.split()
df['word_length'] = df['word_length'].str.len()
df=df[df['word_length'] > 3]
df=df[df['class'] == 'CH3Thailand.csv']

In [ ]:
from keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import LSTM
from keras.layers import Embedding
from keras.layers import SpatialDropout1D
from keras.utils import to_categorical
import numpy as np

MAX_WORDS = 10000
MAX_SEQUENCE_LENGTH = 355
EMBEDDING_DIM = 100

tokenizer = Tokenizer(num_words=MAX_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~')
tokenizer.fit_on_texts(df.message.values)
word_index = tokenizer.word_index
X = tokenizer.texts_to_sequences(df.message.values)
X_train = []
Y_train = []

for x in X:
  for i in range(len(x)-3):
    X_train.append(x[i:i+3])
    Y_train.append(x[i+3])

X_train = np.array(X_train)
Y_train = to_categorical(Y_train, num_classes=MAX_WORDS)

<>:18: SyntaxWarning: invalid escape sequence '\]'
<>:18: SyntaxWarning: invalid escape sequence '\]'
/tmp/ipykernel_1468/3542666661.py:18: SyntaxWarning: invalid escape sequence '\]'
  tokenizer = Tokenizer(num_words=MAX_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~')

ModuleNotFoundError: No module named 'keras.preprocessing.text'

In [ ]:
X_train

In [ ]:
Y_train

In [ ]:
model = Sequential()
model.add(Embedding(MAX_WORDS, EMBEDDING_DIM, input_length=X_train.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(50, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(20, activation='sigmoid'))
model.add(Dense(MAX_WORDS, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

epochs = 50
batch_size = 100

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

In [ ]:
def gen_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    output_text = []
    input_text = seed_text
    for i in range(num_gen_words):
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len,truncating='pre')
        # pred_word_ind = model.predict_classes(pad_encoded,verbose=0)[0]
        predict_x = model.predict(pad_encoded,verbose=0)
        pred_word_ind = np.argmax(predict_x,axis=1)[0]
        pred_word = tokenizer.index_word[pred_word_ind]
        input_text += ' '+pred_word
        output_text.append(pred_word)
    return ' '.join(output_text)

In [ ]:
df['message']

In [ ]:
seed_text  = "ร้องไห้ มีความผิด โดน"
out = gen_text(model, tokenizer, seq_len=3, seed_text=seed_text, num_gen_words=10)
print('Output: '+seed_text+' '+out)

In [ ]:
df['message']